version: '3'

# services
# - - - - - - - - - - - - - - - - - -
services:

  # frontend (nuxt dev server)
  # - - - - - - - - - - - - - - - - - -
  frontend:
    build:
      dockerfile: Dockerfile.frontend.dev
      context: ./frontend
    env_file:
      - ./conf/frontend-dev.env
    restart: "unless-stopped"
    ports:
      - '8080:8080'
    volumes:
      - ./frontend/src:/usr/src/app/src
    networks:
      - dev-network

  # backend-service (nestjs)
  # - - - - - - - - - - - - - - - - - -
  backend:
    build:
      dockerfile: Dockerfile.backend.dev
      context: ./backend
    env_file:
      - ./conf/backend-dev.env
    restart: "no"
    volumes:
      - ./backend/src:/usr/src/app/src
    ports:
      - '3000'
    depends_on:
      - mariadb
    networks:
      - dev-network

  # maria-service
  # - - - - - - - - - - - - - - - - - -
  mariadb:
    image: mariadb
    env_file:
      - ./conf/maria-dev.env
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - dev-network

  # nginx-service
  # - - - - - - - - - - - - - - - - - -
  nginx:
    image: nginx:stable-alpine
    links:
      - backend
      - frontend
    ports:
      - "9000:9000"
    volumes:
      - ./frontend/nginx/default.conf.dev:/etc/nginx/conf.d/default.conf
    networks:
      - dev-network
    depends_on:
      - frontend
      - backend

# networks
# - - - - - - - - - - - - - - - - - -
networks:
  dev-network:
    driver: bridge


