FROM node:12.18.3-alpine3.9 as builder

WORKDIR /usr/src/app

COPY ./package*.json ./

RUN npm install -g @nestjs/cli

RUN npm install #--loglevel=verbose

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:dev"]